version: '3'
services:
  postgres:
    container_name: cadastrodb
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cadastro-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - net
networks:
  net:
    driver: bridge
volumes:
  postgresql:
  postgresql_data: